<a href="https://colab.research.google.com/github/Lu1sV1rus/Metodos_Numericos/blob/main/AlgoritmoQR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#numero de decimales
kk=6
#vectores horizontales
a1=2
a2=2
a3=1
a4=-1
a5=3
a6=1
a7=1
a8=1
a9=2
A=np.array([[a1,a4,a7],[a2,a5,a8],[a3,a6,a9]])
print("A")
print(A)
for i in range(10):
  #U1
  u11=round(((a1**2+a2**2+a3**2)**0.5), kk)
  u1=round(a1/u11, kk)
  u2=round(a2/u11, kk)
  u3=round(a3/u11, kk)
  #U2
  w222=round(((a1*a4+a2*a5+a3*a6)/(a1**2+a2**2+a3**2)), kk)
  w21=round(a4-(w222*a1), kk)
  w22=round(a5-(w222*a2), kk)
  w23=round(a6-(w222*a3), kk)
  u22=round(((w21**2+w22**2+w23**2)**0.5), kk)
  u4=round(w21/u22, kk)
  u5=round(w22/u22, kk)
  u6=round(w23/u22, kk)
  #U3
  w331=round(((a1*a7+a2*a8+a3*a9)/(a1**2+a2**2+a3**2)), kk)
  w332=round(((w21*a7+w22*a8+w23*a9)/(w21**2+w22**2+w23**2)), kk)
  w31=round(a7-(w331*a1)-(w332*w21), kk)
  w32=round(a8-(w331*a2)-(w332*w22), kk)
  w33=round(a9-(w331*a3)-(w332*w23), kk)
  u33=round(((w31**2+w32**2+w33**2)**0.5), kk)
  u7=round(w31/u33, kk)
  u8=round(w32/u33, kk)
  u9=round(w33/u33, kk)
  A=np.array([[a1,a4,a7],[a2,a5,a8],[a3,a6,a9]])
  Q=np.array([[u1,u4,u7],[u2,u5,u8],[u3,u6,u9]])
  Qt=np.array([[u1,u2,u3],[u4,u5,u6],[u7,u8,u9]])
  R=np.dot(Qt,A)
  A1=np.dot(R,Q)
  print("x")
  print(a1,a2,a3)
  print(a4,a5,a6)
  print(a7,a8,a9)
  print("w")
  print(a1,a2,a3)
  print(w21,w22,w23)
  print(w31,w32,w33)
  print("v")
  print(u1,u2,u3)
  print(u4,u5,u6)
  print(u7,u8,u9)
  print("Q")
  print(Q)
  print("R")
  print(R)
  print("A",i+1)
  print(A1)
  print("---------------------")
  a1=round(A1[0][0], kk)
  a4=round(A1[0][1],kk)
  a7=round(A1[0][2],kk)
  a2=round(A1[1][0],kk)
  a5=round(A1[1][1],kk)
  a8=round(A1[1][2],kk)
  a3=round(A1[2][0],kk)
  a6=round(A1[2][1],kk)
  a9=round(A1[2][2],kk)

A
[[ 2 -1  1]
 [ 2  3  1]
 [ 1  1  2]]
x
2 2 1
-1 3 1
1 1 2
w
2 2 1
-2.111112 1.888888 0.444444
-0.162163 -0.486487 1.297297
v
0.666667 0.666667 0.333333
-0.736235 0.658736 0.154997
-0.116248 -0.348743 0.929981
Q
[[ 0.666667 -0.736235 -0.116248]
 [ 0.666667  0.658736 -0.348743]
 [ 0.333333  0.154997  0.929981]]
R
[[ 3.00000100e+00  1.66666700e+00  2.00000000e+00]
 [-1.00000000e-06  2.86744000e+00  2.32495000e-01]
 [-1.00000000e-06 -1.11022302e-16  1.39497100e+00]]
A 1
[[ 3.77777956 -0.80081818  0.92997943]
 [ 1.98912521  1.92492272 -0.78378358]
 [ 0.4649892   0.21621706  1.29729664]]
---------------------
x
3.77778 1.989125 0.464989
-0.800818 1.924923 0.216217
0.929979 -0.783784 1.297297
w
3.77778 1.989125 0.464989
-0.986001 1.827418 0.193424
-0.069558 -0.177897 1.326147
v
0.879637 0.463158 0.10827
-0.472802 0.876274 0.09275
-0.051915 -0.132776 0.989785
Q
[[ 0.879637 -0.472802 -0.051915]
 [ 0.463158  0.876274 -0.132776]
 [ 0.10827   0.09275   0.989785]]
R
[[ 4.29469858e+00  2.10524158e