<a href="https://colab.research.google.com/github/Lu1sV1rus/Metodos_Numericos/blob/main/CuasiNewton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2x2
import sympy as sp
import math
from sympy import symbols, Eq, solve
x, y = symbols("x y")
#Funciones
f1=-1+3*x**2-2*y**2
f2=3*x*y**2-y**3-1
M=[[(sp.diff(f1,x)),(sp.diff(f1,y))],[(sp.diff(f2,x)),(sp.diff(f2,y))]]
print("")
print(M)
print("")


[[6*x, -4*y], [3*y**2, 6*x*y - 3*y**2]]



In [ ]:
def eva(i,x,y):
  g1=-1+3*x**2-2*y**2
  g7=3*x*y**2-y**3-1
  g3=0
  if i==1:
    return float(g1)
  if i==2:
    return float(g7)

def eva2(M,i,j):
  v1=M[i][j]
  a=lambda x,y:v1
  v=a(x,y)
  return float(v)

In [ ]:
#2x2
import numpy as np
#Intervalo
x=0.5
y=0.75
#Numero de iteraciones
iii=4
#No olvidar Matriz
for i in range(iii):
  #Matriz
  M=[[6*x, -4*y], [3*y**2, 6*x*y - 3*y**2]]
  M3=np.array([eva(1,x,y),eva(2,x,y)])
  M2=np.array([[eva2(M,0,0), eva2(M,0,1)], [eva2(M,1,0), eva2(M,1,1)]])
  B1=np.linalg.inv(M2)
  X=B1.dot(M3)
  x=x-X[0]
  y=y-X[1]
  print("J",i+1)
  print(M2)
  print("J-1=F(x)")
  print(B1,"=",M3)
  print("h=",X[0]," k=",X[1])
  print("x=",x," y=",y)
  print("error= ",((X[0])**2+(X[1])**2)**(1/2))
  print("------------------------------------")
  M=[]
  M3=[]
  M2=[]
  B1=[]
  X=[]

J 1
[[ 3.     -3.    ]
 [ 1.6875  0.5625]]
J-1=F(x)
[[ 0.08333333  0.44444444]
 [-0.25        0.44444444]] = [-1.375    -0.578125]
h= -0.37152777777777773  k= 0.08680555555555558
x= 0.8715277777777777  y= 0.6631944444444444
error=  0.3815338702340887
------------------------------------
J 2
[[ 5.22916667 -2.65277778]
 [ 1.31948061  2.14847367]]
J-1=F(x)
[[ 0.14580735  0.18003223]
 [-0.08954728  0.35488029]] = [ 0.39902826 -0.14172673]
h= 0.032665875403883854  k= -0.08602791954272215
x= 0.8388619023738938  y= 0.7492223639871666
error=  0.09202098867514487
------------------------------------
J 3
[[ 5.03317141 -2.99688946]
 [ 1.68400245  2.08696213]]
J-1=F(x)
[[ 0.13420282  0.192716  ]
 [-0.10829036  0.32365981]] = [-0.01160043 -0.0079186 ]
h= -0.0030828507747526846  k= -0.0013067177877040862
x= 0.8419447531486465  y= 0.7505290817748707
error=  0.0033483548611363593
------------------------------------
J 4
[[ 5.05166852 -3.00211633]
 [ 1.68988171  2.10154243]]
J-1=F(x)
[[ 0.13394564  0.1

In [ ]:
#3x3
import sympy as sp
import math
from sympy import symbols, Eq, solve
x, y, z = symbols("x y z")
f1=2*x-3*y+z-4
f2=2*x+y-z+4
f3=x**2+y**2+z**2-4
M=[[(sp.diff(f1,x)),(sp.diff(f1,y)),(sp.diff(f1,z))],[(sp.diff(f2,x)),(sp.diff(f2,y)),(sp.diff(f2,z))],[(sp.diff(f3,x)),(sp.diff(f3,y)),(sp.diff(f3,z))]]
print("")
print(M)
print("")


[[2, -3, 1], [2, 1, -1], [2*x, 2*y, 2*z]]



In [ ]:
def eva3x3(i,x,y,z):
  g1=2*x-3*y+z-4
  g7=2*x+y-z+4
  g3=x**2+y**2+z**2-4
  if i==1:
    return float(g1)
  if i==2:
    return float(g7)
  if i==3:
    return float(g3)
def eva3(M,i,j):
  v1=M[i][j]
  a=lambda x,y,z:v1
  v=a(x,y,z)
  return float(v)

In [ ]:
#3x3
import numpy as np
#Intervalo
x=-0.5
y=-1.5
z=1.5
#Numero de iteraciones
iii=4
#No olvidar la Matriz
for i in range(iii):
  #Matriz
  M=[[2, -3, 1], [2, 1, -1], [2*x, 2*y, 2*z]]
  M3=np.array([eva3x3(1,x,y,z),eva3x3(2,x,y,z),eva3x3(3,x,y,z)])
  M2=np.array([[eva3(M,0,0), eva3(M,0,1), eva3(M,0,2)], [eva3(M,1,0), eva3(M,1,1), eva3(M,1,2)],[eva3(M,2,0), eva3(M,2,1), eva3(M,2,2)]])
  B1=np.linalg.inv(M2)
  X=B1.dot(M3)
  x=x-X[0]
  y=y-X[1]
  z=z-X[2]
  print("J",i+1)
  print(M2)
  print("J-1=F(x)")
  print(B1,"=",M3)
  print("h=",X[0]," j=",X[1]," k=",X[2])
  print("x=",x," y=",y," z=",z)
  print("error= ",((X[0])**2+(X[1])**2+(X[2])**2)**(1/2))
  print("------------------------------------")
  M=[]
  M3=[]
  M2=[]
  B1=[]
  X=[]

J 1
[[ 2. -3.  1.]
 [ 2.  1. -1.]
 [-1. -3.  3.]]
J-1=F(x)
[[-2.22044605e-16  6.00000000e-01  2.00000000e-01]
 [-5.00000000e-01  7.00000000e-01  4.00000000e-01]
 [-5.00000000e-01  9.00000000e-01  8.00000000e-01]] = [1.   0.   0.75]
h= 0.14999999999999983  j= -0.20000000000000012  k= 0.09999999999999998
x= -0.6499999999999998  y= -1.2999999999999998  z= 1.4
error=  0.2692582403567252
------------------------------------
J 2
[[ 2.  -3.   1. ]
 [ 2.   1.  -1. ]
 [-1.3 -2.6  2.8]]
J-1=F(x)
[[ 0.0212766   0.61702128  0.21276596]
 [-0.45744681  0.73404255  0.42553191]
 [-0.41489362  0.96808511  0.85106383]] = [-4.4408921e-16  4.4408921e-16  7.2500000e-02]
h= 0.015425531914893653  j= 0.030851063829787296  k= 0.06170212765957414
x= -0.6654255319148934  y= -1.330851063829787  z= 1.3382978723404257
error=  0.07068866763495686
------------------------------------
J 3
[[ 2.         -3.          1.        ]
 [ 2.          1.         -1.        ]
 [-1.33085106 -2.66170213  2.67659574]]
J-1=F(x)
[[ 0