<a href="https://colab.research.google.com/github/Lu1sV1rus/Metodos_Numericos/blob/main/Newton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2x2
import sympy as sp
import math
from sympy import symbols, Eq, solve
x, y = symbols("x y")
f1=sp.log(x**2+y**2) -sp.sin(x*y)-sp.log(2)-sp.log(3.1416)
f2=sp.exp(x-y) -sp.cos(x*y)
M=[[(sp.diff(f1,x)),(sp.diff(f1,y))],[(sp.diff(f2,x)),(sp.diff(f2,y))]]
print("")
print(M)
print("")


[[2*x/(x**2 + y**2) - y*cos(x*y), -x*cos(x*y) + 2*y/(x**2 + y**2)], [y*sin(x*y) + exp(x - y), x*sin(x*y) - exp(x - y)]]



In [ ]:
def eva(i,x,y):
  g1=-sp.log(x**2+y**2)-sp.log(2)-sp.log(3.1416)
  g2=sp.exp(x-y) -sp.cos(x*y)
  g3=0
  if i==1:
    return float(-g1)
  if i==2:
    return float(-g2)
def eva2(M,i,j):
  v1=M[i][j]
  a=lambda x,y:v1
  v=a(x,y)
  return float(v)
def eva3x3(i,x,y,z):
  g1=2*x-3*y+z-4
  g2=2*x+y-z+4
  g3=x**2+y**2+z**2-4
  if i==1:
    return float(-g1)
  if i==2:
    return float(-g2)
  if i==3:
    return float(-g3)
def eva3(M,i,j):
  v1=M[i][j]
  a=lambda x,y,z:v1
  v=a(x,y,z)
  return float(v)

In [ ]:
#2x2
import numpy as np
x1, y1 = symbols("x1 y1")
#Intervalo
x=1.5
y=1.5
z=0
#Numero de iteraciones
iii=4
#No olvidar la Matriz
for i in range(iii):
  #Matriz
  M=[[8*x - 20, y/2], [y**2/2 + 2, x*y - 5]]
  M3=np.array([eva(1,x,y),eva(2,x,y)])
  M2=np.array([[eva2(M,0,0), eva2(M,0,1)], [eva2(M,1,0), eva2(M,1,1)]])
  print("J",i+1)
  print("J=-F(x)")
  print(M2,"=",M3)
  e1 = Eq((eva2(M,0,0)*x1+eva2(M,0,1)*y1), (eva(1,x,y)))
  e2 = Eq((eva2(M,1,0)*x1+eva2(M,1,1)*y1), (eva(2,x,y)))
  solution = solve((e1, e2), (x1, y1))
  c1=str(solution)
  heva=float(c1[5:c1.index(',')])
  jeva=float(c1[c1.index(',')+6:-1])
  keva=0
  error=((heva)**2+(jeva)**2)**(1/2)
  x=x+heva
  y=y+jeva
  print("h=",heva," j=",jeva)
  print("x=",x," y=",y)
  print("error=",error)
  print("-----------------------------------------------------------------------")
  e1=0
  e2=0
  e3=0
  M=[]
  M3=[]
  M2=[]

J 1
J=-F(x)
[[-20.   0.]
 [  2.  -5.]] = [-8. -8.]
h= 0.4  j= 1.76
x= 0.4  y= 1.76
error= 1.8048822676285565
-----------------------------------------------------------------------
J 2
J=-F(x)
[[-16.8      0.88  ]
 [  3.5488  -4.296 ]] = [-1.4144  -0.61952]
h= 0.0958936105529315  j= 0.223423474192328
x= 0.4958936105529315  y= 1.983423474192328
error= 0.24313295409106342
-----------------------------------------------------------------------
J 3
J=-F(x)
[[-16.03285112   0.99171174]
 [  3.96698434  -4.01643297]] = [-0.04926185 -0.05008482]
h= 0.00409400397173377  j= 0.0165135746086753
x= 0.4999876145246653  y= 1.9999370488010033
error= 0.017013495081165935
-----------------------------------------------------------------------
J 4
J=-F(x)
[[-16.00009908   0.99996852]
 [  3.9998741   -4.00005625]] = [-0.00013522 -0.00020227]
h= 1.23853258838119e-05  j= 6.29504120552915e-05
x= 0.4999999998505491  y= 1.9999999992130586
error= 6.415723400505363e-05
-------------------------------------------

In [ ]:
#3x3
import sympy as sp
import math
from sympy import symbols, Eq, solve
x, y, z = symbols("x y z")
f1=2*x-3*y+z-4
f2=2*x+y-z+4
f3=x**2+y**2+z**2-4
M=[[(sp.diff(f1,x)),(sp.diff(f1,y)),(sp.diff(f1,z))],[(sp.diff(f2,x)),(sp.diff(f2,y)),(sp.diff(f2,z))],[(sp.diff(f3,x)),(sp.diff(f3,y)),(sp.diff(f3,z))]]
print("")
print(M)
print("")


[[2, -3, 1], [2, 1, -1], [2*x, 2*y, 2*z]]



In [ ]:
#3x3
import numpy as np
x1, y1, z1 = symbols("x1 y1 z1")
#Intervalo
x=-0.5
y=-1.5
z=1.5
#Numero de iteraciones
iii=4
#No olvidar la Matriz
for i in range(iii):
  #Matriz
  M=[[2, -3, 1], [2, 1, -1], [2*x, 2*y, 2*z]]
  M3=np.array([eva3x3(1,x,y,z),eva3x3(2,x,y,z),eva3x3(3,x,y,z)])
  M2=np.array([[eva3(M,0,0), eva3(M,0,1), eva3(M,0,2)], [eva3(M,1,0), eva3(M,1,1), eva3(M,1,2)], [eva3(M,2,0), eva3(M,2,1), eva3(M,2,2)]])
  print("J",i+1)
  print("J=-F(x)")
  print(M2,"=",M3)
  e1 = Eq((eva3(M,0,0)*x1+eva3(M,0,1)*y1+eva3(M,0,2)*z1), (eva3x3(1,x,y,z)))
  e2 = Eq((eva3(M,1,0)*x1+eva3(M,1,1)*y1+eva3(M,1,2)*z1), (eva3x3(2,x,y,z)))
  e3 = Eq((eva3(M,2,0)*x1+eva3(M,2,1)*y1+eva3(M,2,2)*z1), (eva3x3(3,x,y,z)))
  solution = solve((e1, e2, e3), (x1, y1, z1))
  c1=str(solution)
  heva=float(c1[5:c1.index('y')-2])
  jeva=float(c1[c1.index('y')+3:c1.index('z')-2])
  keva=float(c1[c1.index('z')+3:-1])
  error=((heva)**2+(jeva)**2+(keva)**2)**(1/2)
  x=x+heva
  y=y+jeva
  z=z+keva
  print("h=",heva," j=",jeva," k=",keva)
  print("x=",x," y=",y," z=",z)
  print("error=",error)
  print("-----------------------------------------------------------------------")
  e1=0
  e2=0
  e3=0
  M=[]
  M3=[]
  M2=[]

J 1
J=-F(x)
[[ 2. -3.  1.]
 [ 2.  1. -1.]
 [-1. -3.  3.]] = [-1.   -0.   -0.75]
h= -0.15  j= 0.2  k= -0.1
x= -0.65  y= -1.3  z= 1.4
error= 0.26925824035672524
-----------------------------------------------------------------------
J 2
J=-F(x)
[[ 2.  -3.   1. ]
 [ 2.   1.  -1. ]
 [-1.3 -2.6  2.8]] = [-0.     -0.     -0.0725]
h= -0.0154255319148936  j= -0.0308510638297872  k= -0.0617021276595743
x= -0.6654255319148936  y= -1.3308510638297872  z= 1.3382978723404255
error= 0.07068866763495694
-----------------------------------------------------------------------
J 3
J=-F(x)
[[ 2.         -3.          1.        ]
 [ 2.          1.         -1.        ]
 [-1.33085106 -2.66170213  2.67659574]] = [-0.         -0.         -0.00499689]
h= -0.0012331516062182  j= -0.0024663032124364  k= -0.0049326064248728
x= -0.6666586835211118  y= -1.3333173670422236  z= 1.3333652659155528
error= 0.005651010578851278
-----------------------------------------------------------------------
J 4
J=-F(x)
[[ 2.      